//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOP.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MOP.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ### Changes
        ///
        ///- Updated links
        ///
        ///### Bug Fixed
        ///
        ///- Fixed an error when loading items list.
        /// </summary>
        internal static string changelog {
            get {
                return ResourceManager.GetString("changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bruno Salgado
        ///Crate Fondler 6000
        ///Tom Johansson
        ///Donal Magrane
        ///Claudiu Rossi.
        /// </summary>
        internal static string donates {
            get {
                return ResourceManager.GetString("donates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alternatorbeltID,alternator belt
        ///batteryID,battery
        ///BeerCaseID,beercase
        ///BoozeID,booze
        ///brakefluidID,brakefluid
        ///cigarettesID,cigarettes
        ///coolantID,coolant
        ///fireextinguisherID,fireextinguisher
        ///grillcharcoalID,grillcharcoal
        ///groundcoffeeID,groundcoffee
        ///juiceconcentrateID,juiceconcentrate
        ///lightbulbID,light bulb
        ///lightbulbboxID,light bulb box
        ///macaronboxID,macaronbox
        ///milkID,milk,
        ///mosquitosprayID,mosquitospray
        ///motoroilID,motoroil
        ///oilfilterID,oil filter
        ///pikeID,pike
        ///pizzaID,pizza
        ///SausagesID,sausages
        ///shoppingbagID,shopping [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string itemcounter_to_transform {
            get {
                return ResourceManager.GetString("itemcounter_to_transform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] mop {
            get {
                object obj = ResourceManager.GetObject("mop", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sources {
            get {
                object obj = ResourceManager.GetObject("sources", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
